### ISSUE TITLE
how can I trigger onchange event ?

### ISSUE THREAD

**Issue by ishara119** [changhuixu/date-range-picker#5]
i want to fire a methon, on date a range select,
can anyone suggest me a way please?

**Comment by changhuixu** [comment]
In `DateRangePickerComponent`, there is an event `(dateRangeChange)` which emits the new `DateRange`. Is this what you want?

**Comment by ishara119** [comment]
exactly 

thanks

**Comment by changhuixu** [comment]
You are welcome.
